<?php

namespace HO\Bundle\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MilestoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MilestoneRepository extends EntityRepository
{
}
